FORMAT: 1A
HOST: http://vt-ala02:9090/

# CDSRecommendation

Simple API to collect CDS Recommendation for a given patient 

## Recommendations [/api/v1/cds/recommendation/{ehrId}]

Strength is defined as: 

* CRITICAL(5), 
* IMPORTANT(4), 
* VERY_SIGNIFICANT(3), 
* SIGNIFICANT(2), 
* MINOR_SIGNIFICANT(1), 
* NOT_SIGNIFICANT(0), 
* ERROR(Integer.MIN_VALUE);

+ Parameters
    + ehrId (string) - The ehrId to be queried

### List Recommendations for EHR [GET]


+ Response 200 (application/json)

{
  "queryTime": 1454,
  "latestRun": 1464741332672,
  "categories": [
    {
      "strength": 1,
      "label": "MINOR_SIGNIFICANT",
      "totals": 2,
      "guides": [
        "SIRS_Calculation",
        "DemoScreening.v1"
      ]
    }
  ],
  "guides": [
    "DemoRisk1.v1",
    "MEWS.v1",
    "SIRS_Calculation",
    "DemoScreening.v1",
    "MEWS.v2"
  ]
}