FORMAT: 1A
HOST: http://vt-ala02:9090/

# CDSRecommendation

Simple API to collect CDS Recommendation for a given patient 

## Recommendations [/api/v1/cds/recommendation/{ehrId}]


+ Parameters
    + ehrId (string) - The ehrId to be queried

### List Recommendations for EHR [GET]
d

+ Response 200 (application/json)

        [
            {
                "queryTime": 20,
                "latestRun": "2015-08-05T08:40:51.620Z",
                "categories": [
                    {
                    
                        "strength": 5,
                        "label": "Critical", 
                        "totals" : 0
                        
                    },
                    {
                    
                        "strength": 4,
                        "label": "Important", 
                        "totals" : 0
                        
                    },
                    {
                    
                        "strength": 3,
                        "label": "Very significant", 
                        "totals" : 0
                        
                    },
                    {
                        "strength": 2,
                        "label": "Significant", 
                        "totals" : 0
                        
                    },
                    {
                        "strength": 1,
                        "label": "Minor significance", 
                        "totals" : 0
                        
                    },
                     {
                        "strength": 0,
                        "label": "Not significant", 
                        "totals" : 0
                        
                    }
                ]
            }
        ]